### ISSUE TITLE
When installing popochiu 2.0 for godot 4.2.2 multiple non-fatal errors occure

### ISSUE THREAD

**Issue by XaverStiensmeier** [carenalgas/popochiu#250]
### Bug description

![grafik](https://github.com/user-attachments/assets/f1749b91-1596-4e46-8ebd-446f22507fbe)

###  Steps to reproduce

1. Download [Popochiu 2.0 - Beta 3](https://github.com/carenalgas/popochiu/releases/download/v2.0.0-beta3/popochiu-v2.0.0-beta3.zip)github.com/carenalgas/popochiu/releases/download/v1.8.7/popochiu-v1.8.7.zip).
2. Extract it and copy the addons folder into your project folder.

### Expected vs observed behavior
No errors.

### Environment information (please complete):

 - **OS type and version**: Win10
 - **Godot version**: 4.2.2
 - **Plugin version or branch**: popochiu 2.0

**Comment by mapedorr** [comment]
Hi @XaverStiensmeier . This is a known issue related to cycling dependencies. That's why the engine must be restarted once the plugin is enabled. We know how to fix it, but that's planned for Popochiu 2.1.

**Comment by XaverStiensmeier** [comment]
Makes sense. Following https://www.youtube.com/watch?v=-N62S1DHbcs I was able to create a moving character so I, too, cannot detect any issues with the dirty "restart Godot" fix. Great, that an update will remove this irritation.

**Comment by anthonyirwin82** [comment]
I believe this will be fixed with godot 4.4

https://godotengine.org/article/dev-snapshot-godot-4-4-dev-2/#error-less-first-project-import

**Comment by mapedorr** [comment]
I tested installing the plugin on an empty project both in **Godot 4.4.dev2** and **Godot 4.4.dev3**, and in both cases I had to restart the engine to make the plugin to work properly. It is true that you no longer need to restart Godot for the Popochiu dock to appear in the editor, but creating objects (I created a Room) doesn't work as expected.

Also, all the error messages keep appearing when the `popochiu` folder is added to the `addons` folder. I'm working on a proposal to fix this since I already did it about a year ago, but we need to discuss if such changes doesn't affect the understanding and workflow of the plugin (specially when you're adding new functionality to the interfaces and the base objects).
