### ISSUE TITLE
Dialogues not centering with the "AboveCharacterText" node

### ISSUE THREAD

**Issue by BenjaTK** [carenalgas/popochiu#262]
### Bug description

When using the above character dialog style, these lines of code change nothing:
![image](https://github.com/user-attachments/assets/fc0d4d63-166b-452c-9c52-3d539264d0c8)
This is because for some reason you can't use push_color AND the [center] and [right] tags, and removing the `push_color` call that goes before fixes the issue.

###  Steps to reproduce

1. Make a character talk

### Expected vs observed behavior

Expected:
![image](https://github.com/user-attachments/assets/1b80d9c5-38b3-4b8e-9d3a-bce5ab0e90a2)
Observed:
![image](https://github.com/user-attachments/assets/8495f961-7a85-4fe5-b97f-83f172e8ce86)
You can see that only in the second one the color shows up.

### Environment information (please complete):

 - **OS type and version**:  Pop!_OS 22.04 LTS
 - **Godot version**: Godot v4.3.stable
 - **Plugin version or branch**: v2.0.0-beta3

**Comment by BenjaTK** [comment]
![image](https://github.com/user-attachments/assets/22d4c7ad-9eea-4148-a138-18205d3db3d1)
Pretty easy fix tbf

**Comment by stickgrinder** [comment]
Hi @BenjaTK, thank for reporting the fix.

I'm not sure about this, but my guess is that's more of a Godot bug than a Popochiu one.
Can you share the offending script in your screenshot so I can check if there is something we can do to make it work?

Did you try to `push_color` and `push_center` on the text, instead of using `push_color` on a text that already contains bbcode? I see no reason why this would result in errors but it's worth trying.

Thanks

**Comment by stickgrinder** [comment]
@mapedorr I would close this for inactivity. What do you think?
