### ISSUE TITLE
Room scene selection doesn't seem to work for room tab

### ISSUE THREAD

**Issue by XaverStiensmeier** [carenalgas/popochiu#321]
### Bug description

After creating a room and opening the room's scene in main tab, I don't see the room under the Room tab and can't create a Prop as shown in video 1.

###  Steps to reproduce

1. Install Popochiu & restart
2. Create a new room "101"
3. Switch to room
4. You see the message "Open a Room in Main tab to see ..." intead of the room
5. Opening a sub-tab like props shows the greyed out create button (for props Create prop) which doesn't do anything when clicked

### Expected vs observed behavior

No greyed out buttons and a correctly selected room.

### Environment information (please complete):

 - Win10
 - **Godot version**: 4.3
 - **Plugin version or branch**: 2.0

**Comment by stickgrinder** [comment]
@XaverStiensmeier this is hard to reproduce in our environments, because everything seems to work as expected. An possibility is this comes from some "garbage" left in your project. I'm thinking something like #320.

Can you test this with 2.0.1 again? Is it possible for you to share your code with me or @mapedorr so that we can see the problem in the scope of your project?

Thanks

**Comment by stickgrinder** [comment]
Closed for inactivity
